OUTPUTFILE=sn_rigSolvers
SOURCES= \
   Register.cpp sn_ikfk2Bone_op.cpp sn_chainstretch_op.cpp sn_splinekine_op.cpp sn_slidecurve_op.cpp sn_spring_op.cpp sn_squashstretch_op.cpp sn_null2curve_op.cpp sn_interpose_op.cpp sn_iso4points_op.cpp sn_inverseRotorder_op.cpp

include ../mkfiles/xsiplugin.makefile

